export const COMENZAR_DESCARGA_PELICULAS = 'COMENZAR_DESCARGA_PELICULAS';
export const DESCARGA_PELICULAS_EXITOSA = 'DESCARGA_PELICULAS_EXITOSA';
export const DESCARGA_PELICULAS_ERROR = 'DESCARGA_PELICULAS_ERROR';

export const COMENZAR_DESCARGA_PELICULAS_ALL = 'COMENZAR_DESCARGA_PELICULAS_ALL';
export const DESCARGA_PELICULAS_EXITOSA_ALL = 'DESCARGA_PELICULAS_EXITOSA_ALL';
export const DESCARGA_PELICULAS_ERROR_ALL = 'DESCARGA_PELICULAS_ERROR_ALL';

export const URL_BASE_IMG = 'https://image.tmdb.org/t/p/w500';