//Peliculas top ratest los primeros 5
export const COMENZAR_DESCARGA_PELICULAS = 'COMENZAR_DESCARGA_PELICULAS';
export const DESCARGA_PELICULAS_EXITOSA = 'DESCARGA_PELICULAS_EXITOSA';
export const DESCARGA_PELICULAS_ERROR = 'DESCARGA_PELICULAS_ERROR';

//Peliculas top PLAYING los primeros 5
export const COMENZAR_DESCARGA_PELICULAS_PLAYING = 'COMENZAR_DESCARGA_PELICULAS_PLAYING';
export const DESCARGA_PELICULAS_EXITOSA_PLAYING  = 'DESCARGA_PELICULAS_EXITOSA_PLAYING';
export const DESCARGA_PELICULAS_ERROR_PLAYING  = 'DESCARGA_PELICULAS_ERROR_PLAYING';

//Peliculas top PLAYING los primeros 5
export const COMENZAR_DESCARGA_PELICULAS_PLAYING_ALL = 'COMENZAR_DESCARGA_PELICULAS_PLAYING_ALL';
export const DESCARGA_PELICULAS_EXITOSA_PLAYING_ALL  = 'DESCARGA_PELICULAS_EXITOSA_PLAYING_ALL';
export const DESCARGA_PELICULAS_ERROR_PLAYING_ALL  = 'DESCARGA_PELICULAS_ERROR_PLAYING_ALL';

//peliculas mas populares todos de la primera pagin
export const COMENZAR_DESCARGA_PELICULAS_ALL = 'COMENZAR_DESCARGA_PELICULAS_ALL';
export const DESCARGA_PELICULAS_EXITOSA_ALL = 'DESCARGA_PELICULAS_EXITOSA_ALL';
export const DESCARGA_PELICULAS_ERROR_ALL = 'DESCARGA_PELICULAS_ERROR_ALL';

//Busqueda de Peliculas
export const COMENZAR_DESCARGA_PELICULAS_BUSQUEDA = 'COMENZAR_DESCARGA_PELICULAS_BUSQUEDA';
export const DESCARGA_PELICULAS_EXITOSA_BUSQUEDA  = 'DESCARGA_PELICULAS_EXITOSA_BUSQUEDA';
export const DESCARGA_PELICULAS_ERROR_BUSQUEDA  = 'DESCARGA_PELICULAS_ERROR_BUSQUEDA';

//Pelicula en especifico
export const COMENZAR_DESCARGA_PELICULA = 'COMENZAR_DESCARGA_PELICULA';
export const DESCARGA_PELICULA_EXITOSA = 'DESCARGA_PELICULA_EXITOSA';
export const DESCARGA_PELICULA_ERROR = 'DESCARGA_PELICULA_ERROR';

//para consultar las imagenes de peliculas
export const URL_BASE_IMG = 'https://image.tmdb.org/t/p/w500';


