export const COMENZAR_DESCARGA_PELICULAS = 'COMENZAR_DESCARGA_PELICULAS';
export const DESCARGA_PELICULAS_EXITOSA = 'DESCARGA_PELICULAS_EXITOSA';
export const DESCARGA_PELICULAS_ERROR = 'DESCARGA_PELICULAS_ERROR';